// Code generated by ent, DO NOT EDIT.

package ent

import (
	"finance/ent/creditcard"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CreditCard is the model entity for the CreditCard schema.
type CreditCard struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditCard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditcard.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditCard fields.
func (cc *CreditCard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditcard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cc.ID = int(value.Int64)
		default:
			cc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditCard.
// This includes values selected through modifiers, order, etc.
func (cc *CreditCard) Value(name string) (ent.Value, error) {
	return cc.selectValues.Get(name)
}

// Update returns a builder for updating this CreditCard.
// Note that you need to call CreditCard.Unwrap() before calling this method if this CreditCard
// was returned from a transaction, and the transaction was committed or rolled back.
func (cc *CreditCard) Update() *CreditCardUpdateOne {
	return NewCreditCardClient(cc.config).UpdateOne(cc)
}

// Unwrap unwraps the CreditCard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cc *CreditCard) Unwrap() *CreditCard {
	_tx, ok := cc.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditCard is not a transactional entity")
	}
	cc.config.driver = _tx.drv
	return cc
}

// String implements the fmt.Stringer.
func (cc *CreditCard) String() string {
	var builder strings.Builder
	builder.WriteString("CreditCard(")
	builder.WriteString(fmt.Sprintf("id=%v", cc.ID))
	builder.WriteByte(')')
	return builder.String()
}

// CreditCards is a parsable slice of CreditCard.
type CreditCards []*CreditCard
