// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"finance/ent/creditcard"
	"finance/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CreditCardDelete is the builder for deleting a CreditCard entity.
type CreditCardDelete struct {
	config
	hooks    []Hook
	mutation *CreditCardMutation
}

// Where appends a list predicates to the CreditCardDelete builder.
func (ccd *CreditCardDelete) Where(ps ...predicate.CreditCard) *CreditCardDelete {
	ccd.mutation.Where(ps...)
	return ccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ccd *CreditCardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ccd.sqlExec, ccd.mutation, ccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ccd *CreditCardDelete) ExecX(ctx context.Context) int {
	n, err := ccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ccd *CreditCardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(creditcard.Table, sqlgraph.NewFieldSpec(creditcard.FieldID, field.TypeInt))
	if ps := ccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ccd.mutation.done = true
	return affected, err
}

// CreditCardDeleteOne is the builder for deleting a single CreditCard entity.
type CreditCardDeleteOne struct {
	ccd *CreditCardDelete
}

// Where appends a list predicates to the CreditCardDelete builder.
func (ccdo *CreditCardDeleteOne) Where(ps ...predicate.CreditCard) *CreditCardDeleteOne {
	ccdo.ccd.mutation.Where(ps...)
	return ccdo
}

// Exec executes the deletion query.
func (ccdo *CreditCardDeleteOne) Exec(ctx context.Context) error {
	n, err := ccdo.ccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{creditcard.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ccdo *CreditCardDeleteOne) ExecX(ctx context.Context) {
	if err := ccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
