// Code generated by ent, DO NOT EDIT.

package ent

import (
	"finance/ent/bank"
	"finance/ent/bank_transfer"
	"finance/ent/category"
	"finance/ent/schema"
	"finance/ent/transaction"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bankFields := schema.Bank{}.Fields()
	_ = bankFields
	// bankDescCreatedAt is the schema descriptor for created_at field.
	bankDescCreatedAt := bankFields[6].Descriptor()
	// bank.DefaultCreatedAt holds the default value on creation for the created_at field.
	bank.DefaultCreatedAt = bankDescCreatedAt.Default.(func() time.Time)
	// bankDescUpdatedAt is the schema descriptor for updated_at field.
	bankDescUpdatedAt := bankFields[7].Descriptor()
	// bank.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bank.DefaultUpdatedAt = bankDescUpdatedAt.Default.(func() time.Time)
	// bank.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bank.UpdateDefaultUpdatedAt = bankDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bankDescID is the schema descriptor for id field.
	bankDescID := bankFields[0].Descriptor()
	// bank.DefaultID holds the default value on creation for the id field.
	bank.DefaultID = bankDescID.Default.(func() uuid.UUID)
	bank_transferFields := schema.Bank_Transfer{}.Fields()
	_ = bank_transferFields
	// bank_transferDescAmount is the schema descriptor for amount field.
	bank_transferDescAmount := bank_transferFields[1].Descriptor()
	// bank_transfer.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	bank_transfer.AmountValidator = bank_transferDescAmount.Validators[0].(func(float64) error)
	// bank_transferDescCreatedAt is the schema descriptor for created_at field.
	bank_transferDescCreatedAt := bank_transferFields[6].Descriptor()
	// bank_transfer.DefaultCreatedAt holds the default value on creation for the created_at field.
	bank_transfer.DefaultCreatedAt = bank_transferDescCreatedAt.Default.(func() time.Time)
	// bank_transferDescUpdatedAt is the schema descriptor for updated_at field.
	bank_transferDescUpdatedAt := bank_transferFields[7].Descriptor()
	// bank_transfer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bank_transfer.DefaultUpdatedAt = bank_transferDescUpdatedAt.Default.(func() time.Time)
	// bank_transfer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bank_transfer.UpdateDefaultUpdatedAt = bank_transferDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bank_transferDescID is the schema descriptor for id field.
	bank_transferDescID := bank_transferFields[0].Descriptor()
	// bank_transfer.DefaultID holds the default value on creation for the id field.
	bank_transfer.DefaultID = bank_transferDescID.Default.(func() uuid.UUID)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescAmount is the schema descriptor for amount field.
	transactionDescAmount := transactionFields[1].Descriptor()
	// transaction.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	transaction.AmountValidator = transactionDescAmount.Validators[0].(func(float64) error)
	// transactionDescTransactionDate is the schema descriptor for transaction_date field.
	transactionDescTransactionDate := transactionFields[7].Descriptor()
	// transaction.DefaultTransactionDate holds the default value on creation for the transaction_date field.
	transaction.DefaultTransactionDate = transactionDescTransactionDate.Default.(func() time.Time)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[9].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionFields[10].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
}
