// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bank is the predicate function for bank builders.
type Bank func(*sql.Selector)

// Bank_Transfer is the predicate function for bank_transfer builders.
type Bank_Transfer func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// CreditCard is the predicate function for creditcard builders.
type CreditCard func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
